// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enterMapProto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol.Player {

  /// <summary>Holder for reflection information generated from enterMapProto.proto</summary>
  public static partial class EnterMapProtoReflection {

    #region Descriptor
    /// <summary>File descriptor for enterMapProto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnterMapProtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNlbnRlck1hcFByb3RvLnByb3RvEg9wcm90b2NvbC5wbGF5ZXIibwoNRW50",
            "ZXJNYXBQcm90bxITCgtjaGFyYWN0ZXJJZBgBIAEoCRITCgtvcmllbnRhdGlv",
            "bhgCIAEoAhIQCghtYXBQb3N0WBgDIAEoAhIQCghtYXBQb3N0WRgEIAEoAhIQ",
            "CghtYXBQb3N0WhgFIAEoAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.Player.EnterMapProto), global::Protocol.Player.EnterMapProto.Parser, new[]{ "CharacterId", "Orientation", "MapPostX", "MapPostY", "MapPostZ" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 
  /// </summary>
  public sealed partial class EnterMapProto : pb::IMessage<EnterMapProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EnterMapProto> _parser = new pb::MessageParser<EnterMapProto>(() => new EnterMapProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EnterMapProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.Player.EnterMapProtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EnterMapProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EnterMapProto(EnterMapProto other) : this() {
      characterId_ = other.characterId_;
      orientation_ = other.orientation_;
      mapPostX_ = other.mapPostX_;
      mapPostY_ = other.mapPostY_;
      mapPostZ_ = other.mapPostZ_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EnterMapProto Clone() {
      return new EnterMapProto(this);
    }

    /// <summary>Field number for the "characterId" field.</summary>
    public const int CharacterIdFieldNumber = 1;
    private string characterId_ = "";
    /// <summary>
    /// 角色id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CharacterId {
      get { return characterId_; }
      set {
        characterId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "orientation" field.</summary>
    public const int OrientationFieldNumber = 2;
    private float orientation_;
    /// <summary>
    /// 朝向
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Orientation {
      get { return orientation_; }
      set {
        orientation_ = value;
      }
    }

    /// <summary>Field number for the "mapPostX" field.</summary>
    public const int MapPostXFieldNumber = 3;
    private float mapPostX_;
    /// <summary>
    /// 地图坐标x
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MapPostX {
      get { return mapPostX_; }
      set {
        mapPostX_ = value;
      }
    }

    /// <summary>Field number for the "mapPostY" field.</summary>
    public const int MapPostYFieldNumber = 4;
    private float mapPostY_;
    /// <summary>
    /// 地图坐标y
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MapPostY {
      get { return mapPostY_; }
      set {
        mapPostY_ = value;
      }
    }

    /// <summary>Field number for the "mapPostZ" field.</summary>
    public const int MapPostZFieldNumber = 5;
    private float mapPostZ_;
    /// <summary>
    /// 地图坐标z
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MapPostZ {
      get { return mapPostZ_; }
      set {
        mapPostZ_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EnterMapProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EnterMapProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CharacterId != other.CharacterId) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Orientation, other.Orientation)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MapPostX, other.MapPostX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MapPostY, other.MapPostY)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MapPostZ, other.MapPostZ)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CharacterId.Length != 0) hash ^= CharacterId.GetHashCode();
      if (Orientation != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Orientation);
      if (MapPostX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MapPostX);
      if (MapPostY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MapPostY);
      if (MapPostZ != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MapPostZ);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CharacterId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CharacterId);
      }
      if (Orientation != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Orientation);
      }
      if (MapPostX != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(MapPostX);
      }
      if (MapPostY != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(MapPostY);
      }
      if (MapPostZ != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(MapPostZ);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CharacterId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CharacterId);
      }
      if (Orientation != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Orientation);
      }
      if (MapPostX != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(MapPostX);
      }
      if (MapPostY != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(MapPostY);
      }
      if (MapPostZ != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(MapPostZ);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CharacterId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CharacterId);
      }
      if (Orientation != 0F) {
        size += 1 + 4;
      }
      if (MapPostX != 0F) {
        size += 1 + 4;
      }
      if (MapPostY != 0F) {
        size += 1 + 4;
      }
      if (MapPostZ != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EnterMapProto other) {
      if (other == null) {
        return;
      }
      if (other.CharacterId.Length != 0) {
        CharacterId = other.CharacterId;
      }
      if (other.Orientation != 0F) {
        Orientation = other.Orientation;
      }
      if (other.MapPostX != 0F) {
        MapPostX = other.MapPostX;
      }
      if (other.MapPostY != 0F) {
        MapPostY = other.MapPostY;
      }
      if (other.MapPostZ != 0F) {
        MapPostZ = other.MapPostZ;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CharacterId = input.ReadString();
            break;
          }
          case 21: {
            Orientation = input.ReadFloat();
            break;
          }
          case 29: {
            MapPostX = input.ReadFloat();
            break;
          }
          case 37: {
            MapPostY = input.ReadFloat();
            break;
          }
          case 45: {
            MapPostZ = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            CharacterId = input.ReadString();
            break;
          }
          case 21: {
            Orientation = input.ReadFloat();
            break;
          }
          case 29: {
            MapPostX = input.ReadFloat();
            break;
          }
          case 37: {
            MapPostY = input.ReadFloat();
            break;
          }
          case 45: {
            MapPostZ = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
